language: r
r:
  - oldrel
  - release
  - devel
warnings_are_errors: true
sudo: required
cache: packages
latex: false

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - devtools

r_github_packages:
  - r-lib/pkgbuild
  - r-lib/callr
  - hadley/pkgdown
  - tidymodels/infer

before_deploy:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: docs
  github_token: $GITHUBTRAVIS
#  target-branch: gh-pages-dev
  target-branch: gh-pages

after_success:
  - Rscript -e 'covr::codecov()'


